//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hertzole.ScriptableValues.Generator {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Hertzole.ScriptableValues.Generator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HSV0001Title {
            get {
                return ResourceManager.GetString("HSV0001Title", resourceCulture);
            }
        }
        
        internal static string HSV0001MessageFormat {
            get {
                return ResourceManager.GetString("HSV0001MessageFormat", resourceCulture);
            }
        }
        
        internal static string HSV0001CodeFixTitle {
            get {
                return ResourceManager.GetString("HSV0001CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string HSV0002Title {
            get {
                return ResourceManager.GetString("HSV0002Title", resourceCulture);
            }
        }
        
        internal static string HSV0002Message {
            get {
                return ResourceManager.GetString("HSV0002Message", resourceCulture);
            }
        }
        
        internal static string HSV0002CodeFixTitle {
            get {
                return ResourceManager.GetString("HSV0002CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string HSV0003Title {
            get {
                return ResourceManager.GetString("HSV0003Title", resourceCulture);
            }
        }
        
        internal static string HSV0003MessageFormat {
            get {
                return ResourceManager.GetString("HSV0003MessageFormat", resourceCulture);
            }
        }
    }
}
