using System;
using System.Text;
using NUnit.Framework;

namespace Hertzole.ScriptableValues.Generator.Tests;

partial class GeneratorTests
{
	public static readonly string[] valueArguments =
	[
		"ValueCallbackType.Changing",
		"ValueCallbackType.Changed"
	];

	[Test]
	public void Value_Field_NoArguments_EmitsChanged()
	{
		string source = /*lang=cs*/@"using System;
using Hertzole.ScriptableValues;

namespace My.Namespace
{
	[GenerateScriptableCallbacks]
	public partial class MyClass
	{
		[GenerateValueCallback]
		public ScriptableBool value;
	}
}";

		string result = /*lang=cs*/$@"// <auto-generated/>
#nullable enable
namespace My.Namespace
{{
	partial class MyClass
	{{
        <SUBSCRIBED_MASK_SUMMARY>
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private enum SubscribedCallbacksMask : byte
        {{
            None = 0,
            valueChanged = 1 << 0
        }}

        <SUBSCRIBED_FIELD_SUMMARY>
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private SubscribedCallbacksMask subscribedCallbacks = SubscribedCallbacksMask.None;

        {GetCacheFieldDescription("value", CallbackType.Value)}
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private static global::System.Action<bool, bool, global::My.Namespace.MyClass> valueScriptableValueCallbackChanged = (oldValue, newValue, context) => {{ context.OnValueChanged(oldValue, newValue); }};

        <SUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
		protected virtual void SubscribeToAllScriptableCallbacks()
		{{
			if ((subscribedCallbacks & SubscribedCallbacksMask.valueChanged) == 0)
			{{
				value.RegisterValueChangedListener(valueScriptableValueCallbackChanged, this);
				subscribedCallbacks |= SubscribedCallbacksMask.valueChanged;
			}}
		}}

        <UNSUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
		protected virtual void UnsubscribeFromAllScriptableCallbacks()
		{{
			if ((subscribedCallbacks & SubscribedCallbacksMask.valueChanged) != 0)
			{{
				value.UnregisterValueChangedListener<global::My.Namespace.MyClass>(valueScriptableValueCallbackChanged);
				subscribedCallbacks &= ~SubscribedCallbacksMask.valueChanged;
			}}
		}}

        {GetCallbackMethodDescription("value", 2, CallbackType.Value, CallbackFlags.PostInvoke)}
		private partial void OnValueChanged(bool oldValue, bool newValue);
	}}
}}";

		AssertGeneratedOutput<ScriptableCallbackGenerator>(source, "My.Namespace.MyClass.g.cs", result);
	}

	[Test]
	public void Value_Field_Arguments_EmitsArgument([ValueSource(nameof(valueArguments))] string argument)
	{
		string source = /*lang=cs*/$@"using System;
using Hertzole.ScriptableValues;

namespace My.Namespace
{{
	[GenerateScriptableCallbacks]
	public partial class MyClass
	{{
		[GenerateValueCallback({argument})]
		public ScriptableBool value;
	}}
}}";

		string changeSuffix = GetChangeSuffix(argument);
		CallbackFlags flags = GetCallbackFlags(argument);

		string result = /*lang=cs*/$@"// <auto-generated/>
#nullable enable
namespace My.Namespace
{{
	partial class MyClass
	{{
        <SUBSCRIBED_MASK_SUMMARY>
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private enum SubscribedCallbacksMask : byte
        {{
            None = 0,
            value{changeSuffix} = 1 << 0
        }}

        <SUBSCRIBED_FIELD_SUMMARY>
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private SubscribedCallbacksMask subscribedCallbacks = SubscribedCallbacksMask.None;

        {GetCacheFieldDescription("value", CallbackType.Value, flags)}
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private static global::System.Action<bool, bool, global::My.Namespace.MyClass> valueScriptableValueCallback{changeSuffix} = (oldValue, newValue, context) => {{ context.OnValue{changeSuffix}(oldValue, newValue); }};

        <SUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
		protected virtual void SubscribeToAllScriptableCallbacks()
		{{
			if ((subscribedCallbacks & SubscribedCallbacksMask.value{changeSuffix}) == 0)
			{{
				value.RegisterValue{changeSuffix}Listener(valueScriptableValueCallback{changeSuffix}, this);
				subscribedCallbacks |= SubscribedCallbacksMask.value{changeSuffix};
			}}
		}}

        <UNSUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
		protected virtual void UnsubscribeFromAllScriptableCallbacks()
		{{
			if ((subscribedCallbacks & SubscribedCallbacksMask.value{changeSuffix}) != 0)
			{{
				value.UnregisterValue{changeSuffix}Listener<global::My.Namespace.MyClass>(valueScriptableValueCallback{changeSuffix});
				subscribedCallbacks &= ~SubscribedCallbacksMask.value{changeSuffix};
			}}
		}}

        {GetCallbackMethodDescription("value", 2, CallbackType.Value, flags)}
		private partial void OnValue{changeSuffix}(bool oldValue, bool newValue);
	}}
}}";

		AssertGeneratedOutput<ScriptableCallbackGenerator>(source, "My.Namespace.MyClass.g.cs", result);
	}
	
		[Test]
	public void Value_Property_NoArguments_EmitsChanged()
	{
		string source = /*lang=cs*/@"using System;
using Hertzole.ScriptableValues;

namespace My.Namespace
{
	[GenerateScriptableCallbacks]
	public partial class MyClass
	{
		[GenerateValueCallback]
		public ScriptableBool Value { get; set; }
	}
}";

		string result = /*lang=cs*/$@"// <auto-generated/>
#nullable enable
namespace My.Namespace
{{
	partial class MyClass
	{{
        <SUBSCRIBED_MASK_SUMMARY>
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private enum SubscribedCallbacksMask : byte
        {{
            None = 0,
            ValueChanged = 1 << 0
        }}

        <SUBSCRIBED_FIELD_SUMMARY>
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private SubscribedCallbacksMask subscribedCallbacks = SubscribedCallbacksMask.None;

        {GetCacheFieldDescription("Value", CallbackType.Value)}
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private static global::System.Action<bool, bool, global::My.Namespace.MyClass> ValueScriptableValueCallbackChanged = (oldValue, newValue, context) => {{ context.OnValueChanged(oldValue, newValue); }};

        <SUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
		protected virtual void SubscribeToAllScriptableCallbacks()
		{{
			if ((subscribedCallbacks & SubscribedCallbacksMask.ValueChanged) == 0)
			{{
				Value.RegisterValueChangedListener(ValueScriptableValueCallbackChanged, this);
				subscribedCallbacks |= SubscribedCallbacksMask.ValueChanged;
			}}
		}}

        <UNSUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
		protected virtual void UnsubscribeFromAllScriptableCallbacks()
		{{
			if ((subscribedCallbacks & SubscribedCallbacksMask.ValueChanged) != 0)
			{{
				Value.UnregisterValueChangedListener<global::My.Namespace.MyClass>(ValueScriptableValueCallbackChanged);
				subscribedCallbacks &= ~SubscribedCallbacksMask.ValueChanged;
			}}
		}}

        {GetCallbackMethodDescription("Value", 2, CallbackType.Value, CallbackFlags.PostInvoke)}
		private partial void OnValueChanged(bool oldValue, bool newValue);
	}}
}}";

		AssertGeneratedOutput<ScriptableCallbackGenerator>(source, "My.Namespace.MyClass.g.cs", result);
	}
	
	[Test]
	public void Value_Property_Arguments_EmitsArgument([ValueSource(nameof(valueArguments))] string argument)
	{
		string source = /*lang=cs*/$@"using System;
using Hertzole.ScriptableValues;

namespace My.Namespace
{{
	[GenerateScriptableCallbacks]
	public partial class MyClass
	{{
		[GenerateValueCallback({argument})]
		public ScriptableBool Value {{ get; set; }}
	}}
}}";

		string changeSuffix = GetChangeSuffix(argument);
		CallbackFlags flags = GetCallbackFlags(argument);

		string result = /*lang=cs*/$@"// <auto-generated/>
#nullable enable
namespace My.Namespace
{{
	partial class MyClass
	{{
        <SUBSCRIBED_MASK_SUMMARY>
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private enum SubscribedCallbacksMask : byte
        {{
            None = 0,
            Value{changeSuffix} = 1 << 0
        }}

        <SUBSCRIBED_FIELD_SUMMARY>
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private SubscribedCallbacksMask subscribedCallbacks = SubscribedCallbacksMask.None;

        {GetCacheFieldDescription("Value", CallbackType.Value, flags)}
#if UNITY_EDITOR
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
		private static global::System.Action<bool, bool, global::My.Namespace.MyClass> ValueScriptableValueCallback{changeSuffix} = (oldValue, newValue, context) => {{ context.OnValue{changeSuffix}(oldValue, newValue); }};

        <SUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
		protected virtual void SubscribeToAllScriptableCallbacks()
		{{
			if ((subscribedCallbacks & SubscribedCallbacksMask.Value{changeSuffix}) == 0)
			{{
				Value.RegisterValue{changeSuffix}Listener(ValueScriptableValueCallback{changeSuffix}, this);
				subscribedCallbacks |= SubscribedCallbacksMask.Value{changeSuffix};
			}}
		}}

        <UNSUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
		[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
		protected virtual void UnsubscribeFromAllScriptableCallbacks()
		{{
			if ((subscribedCallbacks & SubscribedCallbacksMask.Value{changeSuffix}) != 0)
			{{
				Value.UnregisterValue{changeSuffix}Listener<global::My.Namespace.MyClass>(ValueScriptableValueCallback{changeSuffix});
				subscribedCallbacks &= ~SubscribedCallbacksMask.Value{changeSuffix};
			}}
		}}

        {GetCallbackMethodDescription("Value", 2, CallbackType.Value, flags)}
		private partial void OnValue{changeSuffix}(bool oldValue, bool newValue);
	}}
}}";

		AssertGeneratedOutput<ScriptableCallbackGenerator>(source, "My.Namespace.MyClass.g.cs", result);
	}
	
		[Test]
	public void Value_Field_NoNamespace_NoArguments_EmitsChanged()
	{
		string source = /*lang=cs*/@"using System;
using Hertzole.ScriptableValues;

[GenerateScriptableCallbacks]
public partial class MyClass
{
	[GenerateValueCallback]
	public ScriptableBool value;
}";

		string result = /*lang=cs*/$@"// <auto-generated/>
#nullable enable
partial class MyClass
{{
    <SUBSCRIBED_MASK_SUMMARY>
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private enum SubscribedCallbacksMask : byte
    {{
        None = 0,
        valueChanged = 1 << 0
    }}

    <SUBSCRIBED_FIELD_SUMMARY>
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private SubscribedCallbacksMask subscribedCallbacks = SubscribedCallbacksMask.None;

    {GetCacheFieldDescription("value", CallbackType.Value)}
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private static global::System.Action<bool, bool, global::MyClass> valueScriptableValueCallbackChanged = (oldValue, newValue, context) => {{ context.OnValueChanged(oldValue, newValue); }};

    <SUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
	protected virtual void SubscribeToAllScriptableCallbacks()
	{{
		if ((subscribedCallbacks & SubscribedCallbacksMask.valueChanged) == 0)
		{{
			value.RegisterValueChangedListener(valueScriptableValueCallbackChanged, this);
			subscribedCallbacks |= SubscribedCallbacksMask.valueChanged;
		}}
	}}

    <UNSUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
	protected virtual void UnsubscribeFromAllScriptableCallbacks()
	{{
		if ((subscribedCallbacks & SubscribedCallbacksMask.valueChanged) != 0)
		{{
			value.UnregisterValueChangedListener<global::MyClass>(valueScriptableValueCallbackChanged);
			subscribedCallbacks &= ~SubscribedCallbacksMask.valueChanged;
		}}
	}}

    {GetCallbackMethodDescription("value", 1, CallbackType.Value, CallbackFlags.PostInvoke)}
	private partial void OnValueChanged(bool oldValue, bool newValue);
}}";

		AssertGeneratedOutput<ScriptableCallbackGenerator>(source, "MyClass.g.cs", result);
	}

	[Test]
	public void Value_Field_NoNamespace_Arguments_EmitsArgument([ValueSource(nameof(valueArguments))] string argument)
	{
		string source = /*lang=cs*/$@"using System;
using Hertzole.ScriptableValues;

[GenerateScriptableCallbacks]
public partial class MyClass
{{
	[GenerateValueCallback({argument})]
	public ScriptableBool value;
}}";

		string changeSuffix = GetChangeSuffix(argument);
		CallbackFlags flags = GetCallbackFlags(argument);

		string result = /*lang=cs*/$@"// <auto-generated/>
#nullable enable
partial class MyClass
{{
    <SUBSCRIBED_MASK_SUMMARY>
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private enum SubscribedCallbacksMask : byte
    {{
        None = 0,
        value{changeSuffix} = 1 << 0
    }}

    <SUBSCRIBED_FIELD_SUMMARY>
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private SubscribedCallbacksMask subscribedCallbacks = SubscribedCallbacksMask.None;

    {GetCacheFieldDescription("value", CallbackType.Value, flags)}
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private static global::System.Action<bool, bool, global::MyClass> valueScriptableValueCallback{changeSuffix} = (oldValue, newValue, context) => {{ context.OnValue{changeSuffix}(oldValue, newValue); }};

    <SUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
	protected virtual void SubscribeToAllScriptableCallbacks()
	{{
		if ((subscribedCallbacks & SubscribedCallbacksMask.value{changeSuffix}) == 0)
		{{
			value.RegisterValue{changeSuffix}Listener(valueScriptableValueCallback{changeSuffix}, this);
			subscribedCallbacks |= SubscribedCallbacksMask.value{changeSuffix};
		}}
	}}

    <UNSUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
	protected virtual void UnsubscribeFromAllScriptableCallbacks()
	{{
		if ((subscribedCallbacks & SubscribedCallbacksMask.value{changeSuffix}) != 0)
		{{
			value.UnregisterValue{changeSuffix}Listener<global::MyClass>(valueScriptableValueCallback{changeSuffix});
			subscribedCallbacks &= ~SubscribedCallbacksMask.value{changeSuffix};
		}}
	}}

    {GetCallbackMethodDescription("value", 1, CallbackType.Value, flags)}
	private partial void OnValue{changeSuffix}(bool oldValue, bool newValue);
}}";

		AssertGeneratedOutput<ScriptableCallbackGenerator>(source, "MyClass.g.cs", result);
	}
	
		[Test]
	public void Value_Property_NoNamespace_NoArguments_EmitsChanged()
	{
		string source = /*lang=cs*/@"using System;
using Hertzole.ScriptableValues;

[GenerateScriptableCallbacks]
public partial class MyClass
{
	[GenerateValueCallback]
	public ScriptableBool Value { get; set; }
}";

		string result = /*lang=cs*/$@"// <auto-generated/>
#nullable enable
partial class MyClass
{{
    <SUBSCRIBED_MASK_SUMMARY>
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private enum SubscribedCallbacksMask : byte
    {{
        None = 0,
        ValueChanged = 1 << 0
    }}

    <SUBSCRIBED_FIELD_SUMMARY>
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private SubscribedCallbacksMask subscribedCallbacks = SubscribedCallbacksMask.None;

    {GetCacheFieldDescription("Value", CallbackType.Value)}
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private static global::System.Action<bool, bool, global::MyClass> ValueScriptableValueCallbackChanged = (oldValue, newValue, context) => {{ context.OnValueChanged(oldValue, newValue); }};

    <SUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
	protected virtual void SubscribeToAllScriptableCallbacks()
	{{
		if ((subscribedCallbacks & SubscribedCallbacksMask.ValueChanged) == 0)
		{{
			Value.RegisterValueChangedListener(ValueScriptableValueCallbackChanged, this);
			subscribedCallbacks |= SubscribedCallbacksMask.ValueChanged;
		}}
	}}

    <UNSUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
	protected virtual void UnsubscribeFromAllScriptableCallbacks()
	{{
		if ((subscribedCallbacks & SubscribedCallbacksMask.ValueChanged) != 0)
		{{
			Value.UnregisterValueChangedListener<global::MyClass>(ValueScriptableValueCallbackChanged);
			subscribedCallbacks &= ~SubscribedCallbacksMask.ValueChanged;
		}}
	}}

    {GetCallbackMethodDescription("Value", 1, CallbackType.Value, CallbackFlags.PostInvoke)}
	private partial void OnValueChanged(bool oldValue, bool newValue);
}}";

		AssertGeneratedOutput<ScriptableCallbackGenerator>(source, "MyClass.g.cs", result);
	}
	
	[Test]
	public void Value_Property_NoNamespace_Arguments_EmitsArgument([ValueSource(nameof(valueArguments))] string argument)
	{
		string source = /*lang=cs*/$@"using System;
using Hertzole.ScriptableValues;

[GenerateScriptableCallbacks]
public partial class MyClass
{{
	[GenerateValueCallback({argument})]
	public ScriptableBool Value {{ get; set; }}
}}";

		string changeSuffix = GetChangeSuffix(argument);
		CallbackFlags flags = GetCallbackFlags(argument);

		string result = /*lang=cs*/$@"// <auto-generated/>
#nullable enable
partial class MyClass
{{
    <SUBSCRIBED_MASK_SUMMARY>
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private enum SubscribedCallbacksMask : byte
    {{
        None = 0,
        Value{changeSuffix} = 1 << 0
    }}

    <SUBSCRIBED_FIELD_SUMMARY>
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private SubscribedCallbacksMask subscribedCallbacks = SubscribedCallbacksMask.None;

    {GetCacheFieldDescription("Value", CallbackType.Value, flags)}
#if UNITY_EDITOR
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
	private static global::System.Action<bool, bool, global::MyClass> ValueScriptableValueCallback{changeSuffix} = (oldValue, newValue, context) => {{ context.OnValue{changeSuffix}(oldValue, newValue); }};

    <SUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
	protected virtual void SubscribeToAllScriptableCallbacks()
	{{
		if ((subscribedCallbacks & SubscribedCallbacksMask.Value{changeSuffix}) == 0)
		{{
			Value.RegisterValue{changeSuffix}Listener(ValueScriptableValueCallback{changeSuffix}, this);
			subscribedCallbacks |= SubscribedCallbacksMask.Value{changeSuffix};
		}}
	}}

    <UNSUBSCRIBE_TO_ALL_SUMMARY>
#if UNITY_EDITOR
	[global::System.CodeDom.Compiler.GeneratedCode(""<GENERATOR_NAME>"", ""<ASSEMBLY_VERSION>"")]
#endif // UNITY_EDITOR
#if UNITY_INCLUDE_TESTS
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif // UNITY_INCLUDE_TESTS
	protected virtual void UnsubscribeFromAllScriptableCallbacks()
	{{
		if ((subscribedCallbacks & SubscribedCallbacksMask.Value{changeSuffix}) != 0)
		{{
			Value.UnregisterValue{changeSuffix}Listener<global::MyClass>(ValueScriptableValueCallback{changeSuffix});
			subscribedCallbacks &= ~SubscribedCallbacksMask.Value{changeSuffix};
		}}
	}}

    {GetCallbackMethodDescription("Value", 1, CallbackType.Value, flags)}
	private partial void OnValue{changeSuffix}(bool oldValue, bool newValue);
}}";

		AssertGeneratedOutput<ScriptableCallbackGenerator>(source, "MyClass.g.cs", result);
	}

	private static string GetChangeSuffix(string argument)
	{
		return argument == valueArguments[0] ? "Changing" : "Changed";
	}

	private static CallbackFlags GetCallbackFlags(string argument)
	{
		CallbackFlags flags = CallbackFlags.None;
		if (argument == valueArguments[0])
		{
			flags |= CallbackFlags.PreInvoke;
		}
		else if (argument == valueArguments[1])
		{
			flags |= CallbackFlags.PostInvoke;
		}
		
		return flags;
	}

	private static string GetCacheFieldDescription(string name, CallbackType callbackType, CallbackFlags flags = CallbackFlags.None)
	{
		StringBuilder sb = new StringBuilder();
		sb.Append("/// <summary>Cached callback for when <see cref=\"");
		sb.Append(name);
		sb.Append("\" /> is ");
		switch (callbackType)
		{
			case CallbackType.Collection:
			case CallbackType.Pool:
			case CallbackType.Value:
				if ((flags & CallbackFlags.PreInvoke) != 0)
				{
					sb.Append("changing");
				}
				else
				{
					sb.Append("changed");
				}
				break;
			case CallbackType.Event:
				sb.Append("invoked");
				break;
			default:
				throw new ArgumentOutOfRangeException(nameof(callbackType), callbackType, null);
		}
		sb.Append(".</summary>");

		return sb.ToString();
	}

	private static string GetCallbackMethodDescription(string name, int indent, CallbackType callbackType, CallbackFlags flags = CallbackFlags.None)
	{
		StringBuilder sb = new StringBuilder();
		// First line never indents
		sb.AppendLine(DocumentationHelper.GetMethodCallbackDescription(name, in callbackType, in flags).ToString());
		sb.Append('\t', indent);
		switch (callbackType)
		{
			case CallbackType.Value:
				sb.Append("/// <param name=\"oldValue\">");
				sb.Append(DocumentationHelper.GetOldValueDescription(in flags));
				sb.AppendLine("</param>");
				sb.Append('\t', indent);
				sb.Append("/// <param name=\"newValue\">");
				sb.Append(DocumentationHelper.GetNewValueDescription(in flags));
				sb.Append("</param>");
				break;
			case CallbackType.Event:
				break;
			case CallbackType.Collection:
				break;
			case CallbackType.Pool:
				break;
			default:
				throw new ArgumentOutOfRangeException(nameof(callbackType), callbackType, null);
		}

		return sb.ToString();
	}
}