name: Development Package

on:
  push:
    paths-ignore:
      - '*.md'
    branches-ignore:
      - 'dependabot/**'

jobs:    
  package:
    name: Deploy package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: fast-actions/setup-dotnet@v1
      with:
        sdk-version: '8.x'

    - name: Test generator
      run: |
        cd Generator
        dotnet build -c Release
        dotnet test -c Release --no-build --verbosity normal

    - name: Create dev package
      uses: Hertzole/upm-package@master
      id: upm-release
      with:
        branch-name: 'dev-package'
        remove-tests: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
