name: Build documentation
on:
    push:
        branches: ["master"]
        paths:
            - ".github/workflows/docs.yml"
            - "docs/**"
            - "README.md"

concurrency:
    group: docs
    cancel-in-progress: true

permissions:
    contents: read
    id-token: write
    pages: write

jobs:
    build-docs:
        name: Build documentation
        runs-on: ubuntu-latest
        steps:
            # Checkout the repo
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # Setup node
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest

            # Build the documentation
            - name: Build documentation
              run: |
                  cd docs
                  npm install
                  npm run build

            # Upload the documentation to docs branch
            - name: Upload documentation
              run: |
                  git config --global user.name 'github-bot'
                  git config --global user.email 'github-bot@users.noreply.github.com'
                  git branch -d docs &> /dev/null || echo docs branch not found
                  mv "docs/dist" "/tmp/docs"
                  git checkout -b docs
                  rm -rf .
                  mv "/tmp/docs" .
                  git add .
                  git commit -am "Update documentation"
                  git push -f -u origin docs